[images]
  remote_images = ["https://source.unsplash.com/.*", "https://images.unsplash.com/.*", "https://ext.same-assets.com/.*", "https://ugc.same-assets.com/.*"]

[build]
  command = "npm ci --legacy-peer-deps && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NETLIFY_USE_NPM = "true"
  NPM_CONFIG_FUND = "false"
  NPM_CONFIG_AUDIT = "false"
  NPM_FLAGS = "--legacy-peer-deps"
  NETLIFY_SKIP_PREBUILD = "true"
  FORCE_CI = "true"
  # Explicitly disable other package managers
  NETLIFY_USE_YARN = "false"
  NETLIFY_USE_PNPM = "false"
  # Additional npm-specific settings
  NPM_CONFIG_LEGACY_PEER_DEPS = "true"
  NPM_CONFIG_PROGRESS = "false"
  # Force package manager detection
  PACKAGE_MANAGER = "npm"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
