[images]
  remote_images = ["https://source.unsplash.com/.*", "https://images.unsplash.com/.*", "https://ext.same-assets.com/.*", "https://ugc.same-assets.com/.*"]

[build]
  command = "npm ci --legacy-peer-deps && npx prisma migrate deploy && npm run build"
  publish = ".next"

# Force override dashboard settings
[build.environment]
  NODE_VERSION = "18"
  NETLIFY_USE_NPM = "true"
  NPM_CONFIG_LEGACY_PEER_DEPS = "true"

[build.environment]
  NODE_VERSION = "18"
  NETLIFY_USE_NPM = "true"
  NPM_CONFIG_FUND = "false"
  NPM_CONFIG_AUDIT = "false"
  NPM_FLAGS = "--legacy-peer-deps"
  NETLIFY_SKIP_PREBUILD = "true"
  FORCE_CI = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
