import { Metadata } from 'next';
import Link from 'next/link';
import SiteHeader from '@/components/SiteHeader';
import SiteFooter from '@/components/SiteFooter';

export const metadata: Metadata = {
  title: "Terms of Service — Nail The Speech",
  description: "Terms and conditions for using Nail The Speech, the AI wedding speech generator.",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#faf7f4]">
      <SiteHeader />

      <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <div className="bg-white rounded-xl border border-[#e8e1d8] p-8 md:p-12">
          <h1 className="text-3xl font-bold text-[#181615] mb-2">
            Terms of Service
          </h1>
          <p className="text-sm text-[#8f867e] mb-8">Last updated: 3 April 2026</p>

          <div className="space-y-8 text-[#4a4543] leading-relaxed">
            <section>
              <h2 className="text-xl font-semibold text-[#181615] mb-3">1. About the service</h2>
              <p>
                Nail The Speech ("we", "us", "our") provides an AI-powered wedding speech generator at nailthespeech.com (the "Service"). By using the Service, you agree to these terms. If you do not agree, please do not use the Service.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-[#181615] mb-3">2. Eligibility</h2>
              <p>
                You must be at least 16 years old to use the Service. By creating an account, you confirm that you meet this requirement.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-[#181615] mb-3">3. Accounts</h2>
              <p>
                You are responsible for maintaining the security of your account credentials. You are responsible for all activity that occurs under your account. If you believe your account has been compromised, contact us immediately.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-[#181615] mb-3">4. Getting started and Pro access</h2>
              <ul className="list-disc pl-6 space-y-2">
                <li><strong className="text-[#181615]">Getting started:</strong> You can explore the speech generator and see how it works at no cost. The full speech text, editing, and export features require a Pro upgrade.</li>
                <li><strong className="text-[#181615]">Pro access:</strong> A one-time payment (price varies by currency) gives you access to up to 15 speech regenerations, direct editing, version history, and export features for 90 days from the date of purchase.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-[#181615] mb-3">5. Payments and refunds</h2>
              <p>
                Payments are processed securely by Stripe. Pro access is granted immediately upon successful payment and lasts for 90 days. If you are not satisfied with the Service, contact us at <a href="mailto:hello@nailthespeech.com" className="text-[#da5389] hover:underline">hello@nailthespeech.com</a> and we will work with you to make it right, including offering a refund where appropriate.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-[#181615] mb-3">6. Your content</h2>
              <p>
                You own the speeches generated by the Service. You are free to use, edit, and deliver them however you wish. The personal details you provide (names, stories, memories) are used solely to generate your speech and are not shared publicly or used for any other purpose.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-[#181615] mb-3">7. AI-generated content</h2>
              <p>
                Speeches are generated using artificial intelligence. While we strive for high quality, we cannot guarantee that every generated speech will be perfect, factually accurate, or appropriate for your specific situation. You are responsible for reviewing, editing, and approving any speech before delivering it. We strongly recommend practising your speech aloud before the event.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-[#181615] mb-3">8. Acceptable use</h2>
              <p className="mb-3">You agree not to use the Service to:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li>Generate content that is hateful, discriminatory, or intended to harass.</li>
                <li>Generate content for illegal purposes.</li>
                <li>Attempt to reverse-engineer, scrape, or extract the underlying AI prompts or models.</li>
                <li>Resell or commercially redistribute generated speeches at scale.</li>
                <li>Circumvent usage limits or payment requirements.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-[#181615] mb-3">9. Example speeches</h2>
              <p>
                The example speeches on our website are provided for inspiration and reference only. They are curated examples with fictional names and details. You should not copy them verbatim for your own speech.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-[#181615] mb-3">10. Availability</h2>
              <p>
                We aim to keep the Service available at all times but do not guarantee uninterrupted access. We may perform maintenance, updates, or experience technical issues that temporarily affect availability. We are not liable for any loss resulting from Service downtime.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-[#181615] mb-3">11. Limitation of liability</h2>
              <p>
                The Service is provided "as is" without warranties of any kind. To the fullest extent permitted by law, we shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the Service, including but not limited to embarrassment, emotional distress, or reputational harm resulting from the delivery of any speech.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-[#181615] mb-3">12. Data and privacy</h2>
              <p>
                Your use of the Service is also governed by our <Link href="/privacy" className="text-[#da5389] hover:underline">Privacy Policy</Link>, which explains how we collect, use, and protect your data.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-[#181615] mb-3">13. Changes to these terms</h2>
              <p>
                We may update these terms from time to time. Changes will be posted on this page with an updated date. Continued use of the Service after changes constitutes acceptance of the new terms.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-[#181615] mb-3">14. Contact</h2>
              <p>
                If you have questions about these terms, contact us at: <a href="mailto:hello@nailthespeech.com" className="text-[#da5389] hover:underline">hello@nailthespeech.com</a>
              </p>
            </section>
          </div>
        </div>
      </div>

      <SiteFooter />
    </div>
  );
}
